### PR TITLE
Switch from Travis to Circle

### PR DESCRIPTION
**Pull request by bquorning**
I noticed the rather slow build time on #54 and decided to try out Circle CI on this repo. You can compare these build times yourself:

 - https://travis-ci.org/zendesk/kasket/builds/454185343 (“Ran for 6 min 9 sec”) vs
 - https://circleci.com/workflow-run/1b6bc20d-4cf9-4c5b-8158-68bee96af11b (“00:51”).

TODO:

- [ ] Set up CircleCI/GitHub integration.
- [x] Change build badge in Readme.
- [x] #54 must be merged first.

### CODE REVIEW

**Comment by bquorning** [comment]
Rebased.

I need someone with repo admin rights to help me set up the integration.

**Comment by grosser** [comment]
I'd still prefer longer build times over having to use 2 different configuration languages.
Good to try different providers though since maybe that's a consistent benefit and we should switch more 🤷‍♂️

**Comment by grosser** [comment]
tried adding it, but did not show up under the zendesk repos in circle ci :(

**Comment by bquorning** [comment]
Closing in favor of #56.

**Comment by grosser** [comment]
maybe we should use it for classic :D

**Comment by craig-day** [comment]
Thats the dream. But I guess we have to go through vendor review with them or something.

**Comment by grosser** [comment]
make the dream come true :D
... having vendor review done would enable a bunch more 1-off uses too
and telling travis that "this is faster on circle ci" is also a good
argument :D

**Pull request closed without merging**
