### PR TITLE
do not query db for where(id: [1]) style queries, they get created wh…

### PR DESCRIPTION
**Pull request by grosser**
…en using includes with just 1 element

@staugaard @pschambacher 

### Risks
 - None

### CODE REVIEW

**Comment by pschambacher** [comment]
:+1:

**Comment by grosser** [comment]
opting to not do it since it adds a bunch of complexity with minimal gains ...

**Comment by gabetax** [comment]
@grosser I just found myself about to reimplement this PR before I noticed you already wrote it. My specific use case is:

```ruby
> account.tickets.includes(:account)
```

`:inverse_of` stops working the moment you filter results:

```ruby
> account.tickets.take(10).map(&:account).map(&:object_id).uniq
=> [70282965868560]
> account.tickets.where('1 = 1').take(10).map(&:account).map(&:object_id).uniq
=> [70282911171560, 70282999725980, 70283029901200, 70283027797020, 70283025669300, 70283023540860, 70283021632260, 70283019987940, 70283018351240, 70283016683180]
```

And our IdentityMap explicitly disables itself when you open a transaction. 

:+1: if you want to re-open and merge this.

**Comment by grosser** [comment]
this was meant as a performance optimization ... and it fixes the bug ?
@pschambacher will be working on the rails 4.x upgrade in January so maybe not add more weirdness until we are there ?

**Comment by gabetax** [comment]
I benchmarked it, and going through Kasket is only marginally faster than hitting MySQL. Since my use case is not high traffic, I'm going to use `.includes(:account)` with a logging a deprecation warning once we're on Rails 4.

**Comment by pschambacher** [comment]
Add references(:account) and you should be good to go

**Pull request closed without merging**
