### PR TITLE
clear cache after update_column + siplify reload clear + simplify kas…

### PR DESCRIPTION
**Pull request by grosser**
…ket_dirty_methods

@staugaard @pschambacher 

### Risks
 - None

### CODE REVIEW

**Comment by grosser** [comment]
@staugaard reload is different then the others ... why does it need to call clear_local ?

**Comment by staugaard** [comment]
because it need to force you to go to the database.

**Comment by grosser** [comment]
local cache is deleted when we delete a key, so the read will go through to the db:

```
c.with_local_cache { c.read 'xxx'; c.read 'xxx' }
Cache read: xxx
READ LOCAL
Cache read: xxx
READ LOCAL 11
=> 11
zendesk(dev)> c.with_local_cache { c.read 'xxx'; c.delete 'xxx'; c.read 'xxx' }
Cache read: xxx
READ LOCAL
Cache delete: xxx
Cache read: xxx
READ LOCAL
=> nil
```

and deleting goes through to the underlying cache too:

```
c.write 'xxx', 1
Cache write: xxx
=> true
c.read 'xxx'
Cache read: xxx
=> 1
c.with_local_cache { c.read 'xxx'; c.delete 'xxx' }
Cache read: xxx
READ LOCAL
Cache delete: xxx
c.read 'xxx'
Cache read: xxx
=> nil
```

**Comment by grosser** [comment]
@staugaard so can I remove it or do you know how to reproduce the reason it was added ?

**Comment by pschambacher** [comment]
You'll need to lock mysql2 for Travis

**Comment by grosser** [comment]
fixed in https://github.com/zendesk/kasket/pull/23

@staugaard ok to remove the local clear ?

**Comment by staugaard** [comment]
I guess so.

**Comment by grosser** [comment]
- removed reload hacks
 - made reload expire (this did not work on master / added test would be red on master)

good to go ?

**Comment by pschambacher** [comment]
@staugaard I let you give the final validation since you made the remarks

**Comment by staugaard** [comment]
:+1:

**Pull request merged**
